const baseDeDatos = {
    "✏️ ARTICULOS ESCOLARES": {
        imagen: "img/rubros/libreria.png",
        productos: [] 
    /*      { nombre: "Fibrón Ositos", precio: 1200, img: "img/rubros/libreria/LIBRERIA_FIBRONES OSITOS.png" },
            { nombre: "Fibrones Ezco x12", precio: 4500, img: "img/rubros/libreria/escolar_fibrones_ezco_x12.jpg" },
            { nombre: "Fibrón Olami x12", precio: 4200, img: "img/rubros/libreria/escolar_fibron_olami_x12.jpg" },
            { nombre: "Fibrón Olami x36", precio: 8900, img: "img/rubros/libreria/escolar_fibron_olami_x36.jpg" },
            { nombre: "Fibrón Olami x48", precio: 11500, img: "img/rubros/libreria/escolar_fibron_olami_x48.jpg" },
            { nombre: "Fibrón Ezco x36", precio: 7800, img: "img/rubros/libreria/escolar_fibron_ezco_x36.jpg" },
            { nombre: "Fibrón Pizarra x4 Básicos", precio: 3500, img: "img/rubros/libreria/escolar_fibron_pizarra_x4_basicos.jpg" },
            { nombre: "Fibrón Pizarra x4 No Básicos", precio: 3500, img: "img/rubros/libreria/escolar_fibron_pizarra_x4_nobasico.jpg" },
            { nombre: "Lapiceras Color x4 Filgo", precio: 2200, img: "img/rubros/libreria/escolar_lapiceras_color_x4_filgo.jpg" },
            { nombre: "Temperas Maped x12", precio: 3800, img: "img/rubros/libreria/escolar_temperas_maped_x12.jpg" },
            { nombre: "Foli N3 Luma", precio: 1500, img: "img/rubros/libreria/escolar_foli_n3_luma.jpg" },
            { nombre: "Lapiceras Dolche x12", precio: 5500, img: "img/rubros/libreria/escolar_lapiceras_dolche_x12.jpg" },
            { nombre: "Tijera Maped 17cm", precio: 1800, img: "img/rubros/libreria/escolar_tijera_maped_17cm.jpg" },
            { nombre: "Canopla 20cm", precio: 2500, img: "img/rubros/libreria/escolar_canopla_20cm.jpg" },
            { nombre: "Canopla 20cm x 7cm", precio: 2800, img: "img/rubros/libreria/escolar_canopla_20cmx7cm.jpg" },
            { nombre: "Estuche de Arte 42 piezas Nena", precio: 12500, img: "img/rubros/libreria_escolar/estuche_de_arte_42 piezas_nena.jpg" },
            { nombre: "Estuche de Arte 42 piezas Varón", precio: 12500, img: "img/rubros/libreria_escolar/estuche_de_arte_42 piezas_varon.jpg" },
            { nombre: "Funda Cuadernos 50hj", precio: 900, img: "img/rubros/libreria/escolar_funda_cuadernos_50hj.jpg" },
            { nombre: "Cartuchera Maped 4 Cuerpos", precio: 9500, img: "img/rubros/libreria/escolar_cartuchera_maped_4cuerpos.jpg" },
            { nombre: "Colores Filgo x12 Largos", precio: 3200, img: "img/rubros/libreria/escolar_colores_filgo_x12largos.jpg" },
            { nombre: "Set Geometría Económico", precio: 1800, img: "img/rubros/libreria/escolar_set_geometria_economico.jpg" },
            { nombre: "Tapas N3 Caroeta", precio: 2200, img: "img/rubros/escolar/libreria_tapas_n3_caroeta.jpg" },
            { nombre: "Lápices Negros con Goma x12", precio: 2400, img: "img/rubros/libreria/escolar_lapices_negro_con_goma_x12.jpg" }
        ]*/
    },
    
    /*"🎒 MOCHILAS": {
        imagen: "img/rubros/_rubros_titulos/mochila.jpg",
        productos: [
        { nombre: "Cool Girl", precio: 16900, img: "img/rubros/mochilas/cool_girld.jpg" },
            { nombre: "Dream", precio: 24900, img: "img/rubros/mochilas/dream.jpg" },
            { nombre: "Game", precio: 15000, img: "img/rubros/mochilas/game.jpg" },
            { nombre: "Gamer", precio: 15000, img: "img/rubros/mochilas/gamer.jpg" },
            { nombre: "Mochi 01", precio: 18000, img: "img/rubros/mochilas/mochi_01.jpg" },
            { nombre: "Mochi 03", precio: 18000, img: "img/rubros/mochilas/mochi_03.jpg" },
            { nombre: "Mochi 04", precio: 18000, img: "img/rubros/mochilas/mochi_04.jpg" },
            { nombre: "Moch 05", precio: 18000, img: "img/rubros/mochilas/moch_05.jpg" },
            { nombre: "Mochi 06", precio: 18000, img: "img/rubros/mochilas/mochi_06.jpg" },
            { nombre: "Mochi 07", precio: 18000, img: "img/rubros/mochilas/mochi_07.jpg" },
            { nombre: "Jardín 01", precio: 12000, img: "img/rubros/mochilas/jardin_01.jpg" },
            { nombre: "Lentejuelas", precio: 14000, img: "img/rubros/mochilas/lentejuelas.jpg" },
            { nombre: "Mochila Jardín", precio: 12000, img: "img/rubros/mochilas/mochila_jardin.jpg" }
        ]
    },*/

    /*"🍽️ BAZAR ESCOLAR": {
        imagen: "img/rubros/_rubros_titulos/bazar_escolar.jpg",
        productos: [
            { nombre: "Botella Deportiva multicolor", precio: 4500, img: "img/rubros/bazar_escolar/botella_deportiva_multicolor.jpg" },
            { nombre: "Botella de personaje", precio: 4500, img: "img/rubros/bazar_escolar/botella_deportiva_personajes.jpg" },
            { nombre: "Lonchera Personaje", precio: 8500, img: "img/rubros/bazar_escolar/lonchera_personajes.jpg" },
            { nombre: "Set Jabonera y Toalla 01", precio: 3200, img: "img/rubros/bazar_escolar/set_jaboner_y_toalla.jpg" },
            { nombre: "Set Jabonera y Toalla 02", precio: 3200, img: "img/rubros/bazar_escolar/set_jaboner_y_toalla_02.jpg" },
            { nombre: "Set Jabonera y Toalla 03", precio: 3200, img: "img/rubros/bazar_escolar/set_jaboner_y_toalla_03.jpg" },
            { nombre: "Set Jabonera y Toalla 04", precio: 3200, img: "img/rubros/bazar_escolar/set_jaboner_y_toalla_04.jpg" },
            { nombre: "Set Jabonera y Toalla 05", precio: 3200, img: "img/rubros/bazar_escolar/set_jaboner_y_toalla_05.jpg" },
            { nombre: "Set Jabonera y Toalla 06", precio: 3200, img: "img/rubros/bazar_escolar/set_jaboner_y_toalla_06.jpg" },
            { nombre: "Set Jabonera y Toalla 07", precio: 3200, img: "img/rubros/bazar_escolar/set_jaboner_y_toalla_07.jpg" }
        ]
    },*/
    

    "👗 TEXTIL": {
        imagen: "img/rubros/textil-a.jpg",
        productos: [
            { nombre: "Buzo Dama Darlon (2)", precio: 35000, sub: "Mujer", img: "img/rubros/textil/mujer/BUZO DAMA DARLON (2).jpg" },
            { nombre: "Buzo Dama Darlon", precio: 35000, sub: "Mujer", img: "img/rubros/textil/mujer/BUZO DAMA DARLON.jpg" },
            { nombre: "Buzo Dama Microplar - Talle S", precio: 35000, sub: "Mujer", img: "img/rubros/textil/mujer/BUZO DAMA MICROPLAR - TALLE S.jpg" },
            { nombre: "Buzo Dama Micropolar - Talle S", precio: 35000, sub: "Mujer", img: "img/rubros/textil/mujer/BUZO DAMA MICROPOLAR - TALLE S.jpg" },
            { nombre: "Buzo Dama Micropolar - Talles S M L", precio: 35000, sub: "Mujer", img: "img/rubros/textil/mujer/BUZO DAMA MICROPOLAR - TALLES S M L.jpg" },
            { nombre: "Buzo Dama Micropolar", precio: 35000, sub: "Mujer", img: "img/rubros/textil/mujer/BUZO DAMA MICROPOLAR.jpg" },
            { nombre: "Buzo Unisex Darlon - Talle 1", precio: 39900, sub: "Mujer", img: "img/rubros/textil/mujer/BUZO UNISEX DARLON - TALLE 1.jpg" },
            { nombre: "Buzo Unisex Oversize Frizado", precio: 39900, sub: "Mujer", img: "img/rubros/textil/mujer/BUZO UNISEX OVERSIZE FRIZADO.jpg" },
            { nombre: "Calza Dama Termica", precio: 10000, sub: "Mujer", img: "img/rubros/textil/mujer/CALZA DAMA TERMICA.jpg" },
            { nombre: "Calza Dama Termica_", precio: 10000, sub: "Mujer", img: "img/rubros/textil/mujer/CALZA DAMA TERMICA_.jpg" },
            { nombre: "Campera Dama Frizada - Talles 1 2 3", precio: 35000, sub: "Mujer", img: "img/rubros/textil/mujer/CAMPERA DAMA FRIZADA - TALLES 1 2 3.jpg" },
            { nombre: "Campera Unisex Darlon - Talle 4 al 9", precio: 40000, sub: "Mujer", img: "img/rubros/textil/mujer/CAMPERA UNISEX DARLON - TALLE 4 AL 9.jpg" },
            { nombre: "Campera Unisex Darlon - Talles 4 al 9", precio: 40000, sub: "Mujer", img: "img/rubros/textil/mujer/CAMPERA UNISEX DARLON - TALLES 4 AL 9 .jpg" },
            { nombre: "Media Polera Dama Morley de Algodon - Talles S M L XL", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/MEDIA POLERA DAMA MORLEY DE ALGODON - TALLES S M L XL.jpg" },
            { nombre: "Media Polera Dama Termica", precio: 15000, sub: "Mujer", img: "img/rubros/textil/mujer/MEDIA POLERA DAMA TERMICA.jpg" },
            { nombre: "Media Polera Dama Termica", precio: 15000, sub: "Mujer", img: "img/rubros/textil/mujer/MEDIA POLERA DAMA TERMICA .jpg" },
            { nombre: "Pantalon Dama Darlon - Talle 7", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/PANTALON DAMA DARLON - TALLE 7.jpg" },
            { nombre: "Pantalon Dama Darlon Frizado - Talle 7", precio: 30000, sub: "Mujer", img: "img/rubros/textil/mujer/PANTALON DAMA DARLON FRIZADO - TALLE 7.jpg" },
            { nombre: "Pantalon Dama Darlon Frizado - Talle 7", precio: 30000, sub: "Mujer", img: "img/rubros/textil/mujer/PANTALON DAMA DARLON FRIZADO - TALLE 7.jpg" },
            { nombre: "Pantalon Dama Darlon Frizado - Talle 8", precio: 30000, sub: "Mujer", img: "img/rubros/textil/mujer/PANTALON DAMA DARLON FRIZADO - TALLE 8 .jpg" },
            { nombre: "Pantalon Dama Darlon Frizado - Talles 4 5 6", precio: 30000, sub: "Mujer", img: "img/rubros/textil/mujer/PANTALON DAMA DARLON FRIZADO - TALLES 4 5 6.jpg" },
            { nombre: "Pantalon Dama Lanilla - Talle 3", precio: 30000, sub: "Mujer", img: "img/rubros/textil/mujer/PANTALON DAMA LANILLA - TALLE 3.jpg" },
            { nombre: "Pantalon Dama Morley de Lanilla - Talle 3", precio: 30000, sub: "Mujer", img: "img/rubros/textil/mujer/PANTALON DAMA MORLEY DE LANILLA - TALLE 3.jpg" },
            { nombre: "Pantalon Dama Morley de Lanilla - Talle 5", precio: 30000, sub: "Mujer", img: "img/rubros/textil/mujer/PANTALON DAMA MORLEY DE LANILLA - TALLE 5.jpg" },
            { nombre: "Pantalon Dama Morley de Lanilla con Botones - Talle 3", precio: 30000, sub: "Mujer", img: "img/rubros/textil/mujer/PANTALON DAMA MORLEY DE LANILLA CON BOTONES - TALLE 3.jpg" },
            { nombre: "Pantalon Dama Palazzo Frizado - Talle 6_", precio: 30000, sub: "Mujer", img: "img/rubros/textil/mujer/PANTALON DAMA PALAZZO FRIZADO - TALLE 6.jpg" },
            { nombre: "Pantalon Dama Palazzo Frizado Baguidama", precio: 30000, sub: "Mujer", img: "img/rubros/textil/mujer/PANTALON DAMA PALAZO FRIZADO BAGUIDAMA.jpg" },
            { nombre: "Pantalon Dama Palazzo Frizado", precio: 30000, sub: "Mujer", img: "img/rubros/textil/mujer/PANTALON DAMA PALAZO FRIZADO.jpg" },
            { nombre: "Pantalon Dama Palazzo Frizado_", precio: 30000, sub: "Mujer", img: "img/rubros/textil/mujer/PANTALON DAMA PALAZO FRIZADO .jpg" },
            { nombre: "Pantalon Dama Plush - Talle 4", precio: 30000, sub: "Mujer", img: "img/rubros/textil/mujer/PANTALON DAMA PLUSH - TALLE 4.jpg" },
            { nombre: "Pantalon Dama Sastrero Frizado - Talle 7", precio: 30000, sub: "Mujer", img: "img/rubros/textil/mujer/PANTALON DAMA SASTRERO FRIZADO - TALLE 7.jpg" },
            { nombre: "Pantalon Palazzo Dama Frizado - Talle 7", precio: 30000, sub: "Mujer", img: "img/rubros/textil/mujer/PANTALON PALAZO DAMA FRIZADO - TALLE 7.jpg" },
            { nombre: "Polera Dama Morley de Lanilla - Talles S M L XL", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/POLERA DAMA MORLEY DE LANILLA - TALLES S M L XL.jpg" },
            { nombre: "Polera Dama Morley de Lanilla - Talles S M L XL_", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/POLERA DAMA MORLEY DE LANILLA - TALLES S M L XL-a.jpg" },
            { nombre: "Polera Dama Morley de Lanilla - Talles S M L XL__", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/POLERA DAMA MORLEY DE LANILLA - TALLES S M L XL-b.jpg" },
            { nombre: "Polera Dama Morley de Lanilla - Talles S M L XL___", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/POLERA DAMA MORLEY DE LANILLA - TALLES S M L XL-c.jpg" },
            { nombre: "Polera Dama Morley de Lanilla - Talles S M L XL-d", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/POLERA DAMA MORLEY DE LANILLA - TALLES S M L XL-d.jpg" },
            { nombre: "Polera Morley Lanilla Talle S M L XL Rosa", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/POLERA MORLEY LANILLA TALLE S M L XL ROSA.jpg" },
            { nombre: "Poleron Dama Darlon - Talle S M L XL", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/POLERON DAMA DARLON - TALLE S M L XL.jpg" },
            { nombre: "Remera Dama Lanilla - Talle L", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA LANILLA - TALLE L.jpg" },
            { nombre: "Remera Dama Lanilla - Talle M", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA LANILLA - TALLE M.jpg" },
            { nombre: "Remera Dama Lanilla - Talle S", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA LANILLA - TALLE S.jpg" },
            { nombre: "Remera Dama Lanilla - Talle S-a", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA LANILLA - TALLE S-a.jpg" },
            { nombre: "Remera Dama Modal Estampada - Talle L", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA MODAL ESTAMPADA - TALLE L.jpg" },
            { nombre: "Remera Dama Modal Estampada - Talle S M L XL", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA MODAL ESTAMPADA - TALLE S M L XL.jpg" },
            { nombre: "Remera Dama Modal Estampada - Talle XL", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA MODAL ESTAMPADA - TALLE XL.jpg" },
            { nombre: "Remera Dama Modal Estampada con Brillo - Talle 6", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA MODAL ESTAMPADA CON BRILLO - TALLE 6.jpg" },
            { nombre: "Remera Dama Morley - Talle L", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA MORLEY - TALLE L.jpg" },
            { nombre: "Remera Dama Morley - Talle S", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA MORLEY - TALLE S.jpg" },
            { nombre: "Remera Dama Morley con Algodon Cuello Base - Talles M L XL", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA MORLEY CON ALGODON CUELLO BASE - TALLES M L XL.jpg" },
            { nombre: "Remera Dama Morley con Algodon Cuello Base - Talles M L XL_", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA MORLEY CON ALGODON CUELLO BASE - TALLES M L XL-a.jpg" },
            { nombre: "Remera Dama Morley con Algodon Cuello V - Talles L", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA MORLEY CON ALGODON CUELLO V- TALLES L.jpg" },
            { nombre: "Remera Dama Morley con Algodon Cuello V - Talles M", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA MORLEY CON ALGODON CUELLO V- TALLES M.jpg" },
            { nombre: "Remera Dama Morley con Algodon Cuello V - Talles S", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA MORLEY CON ALGODON CUELLO V- TALLES S.jpg" },
            { nombre: "Remera Dama Morley con Botones - S M L XL", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA MORLEY CON BOTONES - S M L XL.jpg" },
            { nombre: "Remera Dama Morley con Botones - Talles S M L XL", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA MORLEY CON BOTONES - TALLES S M L XL.jpg" },
            { nombre: "Remera Dama Morley de Lanilla - Talle L ", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA MORLEY DE LANILLA - TALLE L .jpg" },
            { nombre: "Remera Dama Morley de Lanilla - Talle L", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA MORLEY DE LANILLA - TALLE L.jpg" },
            { nombre: "Remera Dama Morley de Lanilla - Talle M", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA MORLEY DE LANILLA - TALLE M.jpg" },
            { nombre: "Remera Dama Morley de Lanilla - Talle S", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/REMERA DAMA MORLEY DE LANILLA - TALLE S.jpg" },
            { nombre: "Ruana Dama - Azul", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/RUANA DAMA - AZUL.jpg" },
            { nombre: "Ruana Dama - Beige", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/RUANA DAMA - BEIGE.jpg" },
            { nombre: "Ruana Dama - Chocolate", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/RUANA DAMA - CHOCOLATE.jpg" },
            { nombre: "Ruana Dama - Cuadrille Gama Marron Pastel", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/RUANA DAMA - CUADRILLE GAMA MARRON PASTEL.jpg" },
            { nombre: "Ruana Dama - Cuadrille Marron", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/RUANA DAMA - CUADRILLE MARRON.jpg" },
            { nombre: "Ruana Dama - Cuadrille", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/RUANA DAMA - CUADRILLE.jpg" },
            { nombre: "Ruana Dama - Cuadros Tonos Bordeaux", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/RUANA DAMA - CUADROS TONOS BORDEAUX.jpg" },
            { nombre: "Ruana Dama - Cuadros Tonos Marrones y Grises", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/RUANA DAMA - CUADROS TONOS MARRONES Y GRISES.jpg" },
            { nombre: "Ruana Dama - Cuadros Tonos Marrones", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/RUANA DAMA - CUADROS TONOS MARRONES.jpg" },
            { nombre: "Ruana Dama - Cuadros Tonos Negros y Grises", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/RUANA DAMA - CUADROS TONOS NEGROS Y GRISES.jpg" },
            { nombre: "Ruana Dama - Cuadros Tonos Verdes", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/RUANA DAMA - CUADROS TONOS VERDES.jpg" },
            { nombre: "Ruana Dama - Verde Oscuro", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/RUANA DAMA - VERDE OSCURO.jpg" },
            { nombre: "Ruana Dama - Verde Turquesa", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/RUANA DAMA - VERDE TURQUEZA.jpg" },
            { nombre: "Ruana Dama - Verde", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/RUANA DAMA - VERDE.jpg" },
            { nombre: "Sweter Dama Chenil - Talle 3 4 5", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/SWETER DAMA CHENIL - TALLE 3 4 5.jpg" },
            { nombre: "Sweter Dama Chenil - Talle 3 4 5_", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/SWETER DAMA CHENIL - TALLE 3 4 5-a.jpg" },
            { nombre: "Sweter Dama Con Brillo - Talles 3 4 5 6", precio: 0, sub: "Mujer", img: "img/rubros/textil/mujer/SWETER DAMA CON BRILLO - TALLES 3 4 5 6.jpg" },

        ]
    },

    "🧸 PELUCHES": {
        imagen: "img/rubros/peluches.jpg",
        productos: [
            /*{ nombre: "Peluche Gatito con Dona", precio: 8500, img: "img/rubros/peluches/peluche_gatito_con_dona.jpg" },
            { nombre: "Peluche Oso Corazón", precio: 9200, img: "img/rubros/peluches/peluche_oso_corazon.jpg" },
            { nombre: "Peluche Gatito Refresco", precio: 8500, img: "img/rubros/peluches/peluche_gatito_refresco.jpg" },
            { nombre: "Peluche Almohada Smoochy", precio: 12000, img: "img/rubros/peluches/peluche_almohada_smoochy.jpg" },
            { nombre: "Peluche Osita", precio: 7800, img: "img/rubros/peluches/peluche_osita.jpg" },
            { nombre: "Peluche Almohadon", precio: 10500, img: "img/rubros/peluches/peluche_almohadon.jpg" },
            { nombre: "Peluche Caracol", precio: 6500, img: "img/rubros/peluches/peluche_caracol.jpg" },
            { nombre: "Peluche Gatito con Disfraz", precio: 8900, img: "img/rubros/peluches/peluche_gatito_con_disfraz.jpg" }
        */
            ]
    }
};